= ITP Mitschrift
Raphael Scharrer
ifndef::imagesdir[:imagesdir: images]
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
ifdef::backend-html5[]

== Repository inkl. Github Page

. Order erstellen und in IntelliJ öffnen.
. VCS in IntelliJ aktivieren => Git|Github|Share Project => Inhalt des Doc-as-code Ordner in Projekt Ordner ziehen.
. .env -Datei erstellen mit folgendem Inhalt:

 GIT_GLOBAL_MAIL=<mail>
 GIT_GLOBAL_USER_NAME=<name>

. Docker starten:

 service docker start

. Page erstellen:

 sudo ./run-docker-inside-docker.sh

Die Page wurde nun erstellt und nimmt den Inhalt aus dem index.adoc File.
Aktualisiert wird die Page bei erneutem Ausführen vom letzten oben angeführten Befehl.

== Asciidocs

- PlantUML in Adoc File verlinken:

 [plantuml, <umlName>]
 ----
 include::<relativerPfad>[]
 ----

- PlantUML in Adoc File erstellen:

 [plantuml, <umlName>]
 ----
 @startuml
 class Test1
 class Test2
 class Test3
 Test1 <|-- Test2
 Test1 <|-- Test3
 @enduml
 ----

Beides erzielt das selbe Ergebnis:

[plantuml, UMLdefinition1]
----
include::./plantuml/UmlAsciiDefinition.puml[]
----