@startmindmap
+ HAUPTTHEMA
-- HAUPTAST
--- Untergliederung
--- Untergliederung
-- HAUPTAST
--- Untergliederung
--- Untergliederung
++ HAUPTAST
+++ Untergliederung
+++ Untergliederung
++ HAUPTAST
+++ Untergliederung
+++ Untergliederungs
@endmindmap
